# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketScantron' do
  use_frameworks!
  
  pod 'WeScan', '>= 0.9'
  pod 'JGProgressHUD'
  
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'

end
